### ISSUE TITLE
I would like to know an alternative way to execute single command.

### ISSUE THREAD

**Issue by akhil-naidu** [dokku/ansible-dokku#110]
Presently this is how we can delete an app. Even though ansible provides `shell` and `command` modules => We cannot use them; because of the inbuild dokku security to re-enter the name of the app, 

```
---
- hosts: nodes
  roles:
    - dokku_bot.ansible_dokku

  tasks:
    - name: Delete that app
      dokku_app:
        app: "{{ appTitle }}"
        state: absent
```

Just to destroy one app, this procedure takes a lot of time. I would like to know a better way of handling `single commands` like:
-  `dokku apps:destroy AppName` (requires to manually enter: AppName)
- `dokku git:sync --build AppName https://github.com/path/to/my/repo` (For executing this the second time, we should pass: y/n)

> commands like this need some external input from the user.

**Comment by ltalirz** [comment]
hi @akhil-naidu , how about something like
```yaml
---
- hosts: nodes
  roles:
    - dokku_bot.ansible_dokku

  tasks:
    - name: Delete that app
      dokku_app:
        app: "{{ appTitle }}"
        state: absent
      tags: delete-app
```
and `ansible-playbook playbook.yml --tags delete-app` ?
