### ISSUE TITLE
dokku_ports: doesn't check for existing mappings

### ISSUE THREAD

**Issue by fr3fou** [dokku/ansible-dokku#139]
Running 
```yaml
- name: Configure ports
  dokku_ports:
    app: api
    mappings:
      - http:80:8080
      - http:8080:8080
```
any number of times, always results in Ansible reporting this as "changed"
![image (2)](https://user-images.githubusercontent.com/1344906/144619902-bf2579bc-e857-4d90-91b6-d311f2a00c99.png)
I'd expect Ansible to say `ok` after the first time (given the fact that nothing was changed in between)
