### ISSUE TITLE
Feature request: `dokku nginx:set` support

### ISSUE THREAD

**Issue by louwers** [dokku/ansible-dokku#140]
Would be cool if support for `dokku nginx:set` could be added.

Right now I am doing this, which seems to work well:

```yaml
    - name: check client-max-body-size
      command: dokku nginx:report {{ app_name }} --nginx-client-max-body-size 2>/dev/null
      register: client_max_body_size
      changed_when: false

    - name: set client-max-body-size
      vars:
        max_filesize: 500m
      ansible.builtin.shell: dokku nginx:set {{ app_name }} client-max-body-size {{ max_filesize }}
      when: "client_max_body_size.stdout != max_filesize"
      notify:
      - Rebuild config

  handlers:
    - name: Rebuild config
      command: dokku proxy:build-config --all
```
