### ISSUE TITLE
Docker Image Tag Deployment support

### ISSUE THREAD

**Issue by leonverschuren** [dokku/ansible-dokku#16]
Hi,

As far as I can tell there is no support for Docker Image Tag deployments: the Dokku _tags_ plugin.

Support for this would be really helpful.

**Comment by ltalirz** [comment]
Could you comment on what functionality is missing from the `dokku_image` module?

```yaml
- name: Pull and deploy meilisearch
  dokku_image:
      app: meilisearch
      image: getmeili/meilisearch:v0.24.0rc1
```
