### ISSUE TITLE
Wildcard domains always get added

### ISSUE THREAD

**Issue by mikker** [dokku/ansible-dokku#17]
Using `dokku_domains` a wildcard domain will always get added anew leading to multiple registrations of the same wildcard domain.

I would supply a PR but I'm not the well versed in neither Python nor Ansible, sorry.

**Comment by josegonzalez** [comment]
Can you show how to replicate the issue?

**Comment by mikker** [comment]
Yes, of course – example playbook:

```yaml
---
- hosts: dokku
  roles:
    - ansible-dokku
  remote_user: root
  vars:
    dokku_hostname: example.com
    dokku_version: 0.16.4
    dokku_key_file: /root/.ssh/authorized_keys

  tasks:
    - name: Update system
      apt:
        update_cache: true
        upgrade: full

    - name: Create app
      dokku_app:
        app: example

    - name: Domains
      dokku_domains:
        app: example
        domains:
          - example.com
          - '*.example.com'
```
