### ISSUE TITLE
Wrong VHOST set on AWS ec2

### ISSUE THREAD

**Issue by nielsonsantana** [dokku/ansible-dokku#19]
I tried the fallowing ansible code to install dokku.
```yml
- import_role:
    name: dokku
  vars:
    dokku_key_file: /home/ubuntu/.ssh/authorized_keys
    dokku_hostname: mydomain.com
    dokku_version: 0.17.5
    dokku_plugins:
      - name: clone
        url: https://github.com/crisward/dokku-clone.git
```

```
# dependences
ansible==2.7.12
ansible-dokku==2019.4.3
python==3.7.3
```

**Output**
```bash
ubuntu@ip-172-30-1-86:/home/dokku$ cat HOSTNAME
mydomain.com
ubuntu@ip-172-30-1-86:/home/dokku$ cat VHOST
ip-172-30-1-86.sa-east-1.compute.internal
```
I think that the value for `VHOST` must be `mydomain.com`.
