### ISSUE TITLE
dokku install errors without ssh-keygen

### ISSUE THREAD

**Issue by notapatch** [dokku/ansible-dokku#2]
I'm _really_ happy to see dokku/ansible-dokku! 

ansible-dokku won't complete without the server having ssh-keys generated - it gives a 50 line error only one of which is ssh key related. 

I've done a workaround task for my own playbook.

```
    - name: create ssh key for root
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
```

**Comment by josegonzalez** [comment]
This can be configured via either the `dokku_skip_key_file` or `dokku_key_file` variables. See the [readme](https://github.com/dokku/ansible-dokku#dokku_key_file) for more details.

We should probably bail if `dokku_skip_key_file` is set to `'false'`  and the `dokku_key_file` does not exist...

**Comment by notapatch** [comment]
Fixed when using the latest release v2020.1.1:

When I set it `dokku_skip_file` to false and comment out the copying of the ssh_key. It now errors out with a short error message.

```
- import_role:
    name: dokku_bot.ansible_dokku
  vars:
    dokku_skip_key_file: 'false'
    dokku_users:
      - name: foo
        username: foo
        # ssh_key: "{{ lookup('file', controller_key) }}"
```
## Error Output

```
TASK [dokku_bot.ansible_dokku : sshcommand list dokku] **********
fatal: [foo.example.com]: FAILED! => {"changed": false, 
"cmd": ["sshcommand", 
"list", "dokku"],
 "delta": "0:00:00.014980", 
"end": "2020-01-04 16:28:26.854400", 
"msg": "non-zero return code", 
"rc": 255, 
"start": "2020-01-04 16:28:26.839420", 
"stderr": "authorized_keys is empty for dokku", 
"stderr_lines": ["authorized_keys is empty for dokku"], 
"stdout": "", 
"stdout_lines": []}
...ignoring

TASK [dokku_bot.ansible_dokku : dokku ssh-keys:add] ************
fatal: [foo.example.com]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```
[
The fix was made in Dokku version 0.19.5.](https://github.com/dokku/dokku/releases/tag/v0.19.5)
