### ISSUE TITLE
dokku_vhost_enable 'false' not disabling VHOSTS on install

### ISSUE THREAD

**Issue by austinbachman** [dokku/ansible-dokku#20]
Relevant parts from my playbook:
```
  roles:
    - dokku_bot.ansible_dokku
  vars:
    dokku_vhost_enable: 'false'
    dokku_plugins:
      - name: redis
        url: https://github.com/dokku/dokku-redis.git
```

VHOSTS are not being disabled on dokku install. Creating an app and checking the domains yields:
```
=====> ruby-getting-started domains information
       Domains app enabled:           true
       Domains app vhosts:            ruby-getting-started.server-name
       Domains global enabled:        true
       Domains global vhosts:         server-name
```

However, checking the debconf on the target node gives the following, which makes me think this may actually be an issue with dokku? I've never had this issue when doing an unattended installation without Ansible though, so I'm unsure.
```
* dokku/web_config: false
* dokku/key_file: /root/.ssh/id_rsa.pub
* dokku/skip_key_file: false
* dokku/vhost_enable: false
  dokku/nginx_enable: true
* dokku/hostname: dokku.me
```
