### ISSUE TITLE
Install dokku-daemon Errors with: No such file or directory: 'make'

### ISSUE THREAD

**Issue by notapatch** [dokku/ansible-dokku#24]
When I install:
-  dokku_version: 0.17.7 everything works.
- dokku_version: 0.17.8 it breaks with the following message:

```bash
TASK [dokku_bot.ansible_dokku : install dokku-daemon] *******************************************************************************************
fatal: [my.example.com]: FAILED! => {"changed": false, "cmd": "make install", "msg": "[Errno 2] No such file or directory: 'make': 'make'", "rc": 2}
```

I had a little look around and saw that:

- [In Dokku 0.17.8 the make dependency was removed](https://github.com/dokku/dokku/pull/3587/commits/2cabf0a21fe17d27e81225b94dbb6498bd3f7d7c)

```bash
- Depends: locales, git, **make**, curl, gcc, man-db, netcat, sshcommand (>= 0.6.0), ...
+ Depends: locales, git, curl, man-db, netcat, sshcommand (>= 0.6.0), ...
```

- [Whereas when you install dokku-daemon it uses make](https://github.com/dokku/ansible-dokku/blob/7da6e1d6be2a58c03c90a064707eb3350dd3aeac/tasks/dokku-daemon.yml#L21-L30)

```yaml
  - name: install dokku-daemon
    command: **make** install
    args:
      chdir: /var/lib/dokku-daemon
      creates: /usr/bin/dokku-daemon
    notify:
      - start dokku-daemon
    tags:
      - dokku-daemon
  when: dokku_daemon_install
```
If you do make a change I will be happy to do any testing.
