### ISSUE TITLE
add interface for configuring ACLs

### ISSUE THREAD

**Issue by ltalirz** [dokku/ansible-dokku#44]
it would be super useful to be able to set application ACLs via variables of the ansible role (using the [dokku-acl](https://github.com/dokku-community/dokku-acl) plugin).

if I find some time to do this, I'll look into adding this myself.
happy for hints on what best to "copy"

**Comment by josegonzalez** [comment]
Not sure, I don't even know what the output looks like. Might be worth manually adding/removing/listing users in various states and posting the output here as a start :)

**Comment by ltalirz** [comment]
Proposition: 2 new modules
```
dokku_acl_app:
  users:
   - a
   - b
```

```
dokku_acl_service
   type: ...
   users:
    -...
```
For these modules, before they do anything they check the list of users for the app/service; and they only do stuff if the specified list differs from the one they find.


If we want, we can also add a user-centric module on top that only queries the current status (not sure it's really needed to get started)
```
dokku_acl_allowed:
  user: ...
  entity: app/service  # name to decide
  type: ... # only needed if entity=service
  
```
