### ISSUE TITLE
domains not created

### ISSUE THREAD

**Issue by notapatch** [dokku/ansible-dokku#5]
When I try to run this playbook on Ubuntu 16.04 the domain is not created.

Playbook.yml

```
---
- hosts: all
  roles:
    - dokku_bot.ansible_dokku
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    dokku_version: '0.15.2'
    dokku_skip_key_file: true
  become: yes

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Create a dokku app
      dokku_app:
        app: hello-world

    - name: domains:add hello-world dokku.me
      dokku_domains:
        app: hello-world
        domains:
          - dokku.me
```

Error Message is:

```
fatal: [me]: 
  FAILED! => {"changed": false, "meta": 
      {"error": "Command 'dokku --quiet domains hello-world' returned non-zero exit status 1", "present": false},
        "msg": "Command 'dokku --quiet domains hello-world' returned non-zero exit status 1"}
```

Running Dokku query command on the server after the playbook has finished

```
root@me:~# dokku apps:list
=====> My Apps
hello-world

root@me:~# dokku domains:report
=====> hello-world domains information
       Domains app enabled:           true
       Domains app vhosts:
       Domains global enabled:        true
       Domains global vhosts:         dokku.me
```

Running Dokku commands on the server does create the domain

```
root@me:~# dokku domains:add hello-world dokku.me
-----> Added dokku.me to hello-world
 !     No web listeners specified for hello-world

root@me:~# dokku domains:report
=====> hello-world domains information
       Domains app enabled:           true
       Domains app vhosts:            dokku.me
       Domains global enabled:        true
       Domains global vhosts:         dokku.me

```
