### ISSUE TITLE
dokku_config: allow config:set --global

### ISSUE THREAD

**Issue by decentral1se** [dokku/ansible-dokku#52]
```
dokku config:set --global DOKKU_LETSENCRYPT_EMAIL=your@email.tld
```

AFAICT, it isn't possible now and only scoped to an app?

Up for accepting a PR to allow for global config setting?

Very useful for initial provisioning of a host when letsencrypt is installed also.

**Comment by decentral1se** [comment]
API could be:

```yaml
- name: set LE global email
  dokku_config:
    global: True
    config:
      DOKKU_LETSENCRYPT_EMAIL: your@email.tld
```

**Comment by josegonzalez** [comment]
Partial PR here: https://github.com/dokku/ansible-dokku/pull/51

But an alternate implementation is always welcome.

**Comment by nerg4l** [comment]
By looking at the linked PR and the code it seems it is doable at the moment by setting `--global` for the app name. It is a dirty hack but should work until a proper implementation.

```
- name: set LE global email
  dokku_config:
    app: '--global'
    config:
      DOKKU_LETSENCRYPT_EMAIL: your@email.tld
```

**Comment by iloveitaly** [comment]
Worth noting that `DOKKU_LETSENCRYPT_EMAIL` doesn't work anymore, you'll need to do something like 

```
    - name: set letsencrypt email and request certificate
      block:
        - name: Your pre-task (dependency for dokku_letsencrypt)
          ansible.builtin.shell: dokku letsencrypt:set app email email@domain

        - name: letsencrypt
          dokku_letsencrypt:
            app: *appname
```

Would be great if we could add an `email` param to `dokku_letsencrypt`!
