### ISSUE TITLE
Add dokku_deploy module

### ISSUE THREAD

**Issue by decentral1se** [dokku/ansible-dokku#53]
Will aim to get to it if no one else does :sun_with_face:

**Comment by decentral1se** [comment]
Oh wait, it appears that "dokku clone" does this? 

Is this the intended interface for deploying an application?

**Comment by josegonzalez** [comment]
What exactly are you trying to do?

**Comment by decentral1se** [comment]
I have a VPS with Dokku configured and I'm creating and deploying a new Keycloak.org instance with Ansible and the Dokku library modules. The final task is "dokku deploy keycloak" where I re-deploy the application to get the mounts in place with the LE certificates.

``` yaml
- hosts: foobar
  tasks:
    - name: Create the Keycloak Dokku application
      dokku_app:
        app: keycloak
      become: true
      become_user: dokku

    - name: Configure the environment
      dokku_config:
        app: keycloak
        config:
          DB_VENDOR: h2
          KEYCLOAK_USER: autonomic
          KEYCLOAK_PASSWORD: autonomic
          PROXY_ADDRESS_FORWARDING: "true"
          DOKKU_LETSENCRYPT_SERVER: staging
      become: true
      become_user: dokku

    - name: Clone the application onto the Dokku host
      dokku_clone:
        app: keycloak
        repository: git@gitlab.com:autonomic-cooperative/keycloak-dokku.git
      become: true
      become_user: dokku

    - name: Remove default ports proxying
      dokku_ports:
        app: keycloak
        mappings:
          - http:80:5000
        state: absent
      become: true
      become_user: dokku

    - name: Set default HTTP ports proxying for Keycloak
      dokku_ports:
        app: keycloak
        mappings:
          - http:80:8080
        state: present
      become: true
      become_user: dokku

    - name: Setup LE certificates
      shell: dokku letsencrypt keycloak
      args:
        creates: /home/dokku/keycloak/letsencrypt/
      become: true
      become_user: dokku

    - name: Mount LE certificates into the Keycloak container
      dokku_storage:
        app: keycloak
        mounts:
          - "/home/dokku/keycloak/letsencrypt/certs/current/key.pem:/etc/x509/https/tls.key"
          - "/home/dokku/keycloak/letsencrypt/certs/current/cert.pem:/etc/x509/https/tls.crt"
      become: true
      become_user: dokku

    - name: Deploy the application
      shell: dokku deploy keycloak
      become: true
      become_user: dokku
```

**Comment by decentral1se** [comment]
```yaml
    - name: Deploy the application
      shell: dokku deploy keycloak
      become: true
      become_user: dokku
```

Could be:

```yaml
- name: Deploy the application
  dokku_deploy:
    app: keycloak
    force: True
```

Where `force` makes sure it re-deploys if the app is already deployed. Without `force` you will get a idempotent task which does nothing.
