### ISSUE TITLE
dokku_config: allow list type

### ISSUE THREAD

**Issue by decentral1se** [dokku/ansible-dokku#55]
>  TASK [Configure the environment] *************************************************************************************************************************************************************************
fatal: [gitea]: FAILED! => {"changed": false, "meta": {"error": "All values must be keys, found invalid types for WHITELISTED_URIS", "present": false}, "msg": "All values must be keys, found invalid types for WHITELISTED_URIS"}

https://docs.gitea.io/en-us/config-cheat-sheet/

> WHITELISTED_URIS: <empty>: If non-empty, list of POSIX regex patterns matching OpenID URI’s to permit.

So, I need to add the following config:

```yaml
    - name: config env
      dokku_config:
        app: gitea
        config:
          WHITELISTED_URIS: ["foo.com"]
```
