### ISSUE TITLE
dokku_config will not set boolean values

### ISSUE THREAD

**Issue by notapatch** [dokku/ansible-dokku#6]
dokku_config works in general but not when the value is boolean.

### Environment
Mac OS: 10.14.4
ansible 2.7.8
python: 3.7.2

### Steps to reproduce
1. Run following playbook script

```
---
- hosts: all
  roles:
    - dokku_bot.ansible_dokku
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    dokku_version: '0.15.2'
    dokku_skip_key_file: true
  become: yes

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Create a dokku app
      dokku_app:
        app: hello-world

    # works as expected
    - name: config:set hello-world  KEY=VALUE_1
      dokku_config:
        app: hello-world
        config:
          KEY: VALUE_1

    # add the key but leaves the value empty
    - name: config:set hello-world  KEY_2=false
      dokku_config:
        app: hello-world
        config:
          # tried different ansible boolean values (no, false)
          KEY_2: false

    # errors out
    - name: config:set hello-world  KEY_3=TRUE
      dokku_config:
        app: hello-world
        config:
          # tried different ansible boolean values (yes, True, TRUE)
          KEY_3: TRUE
```

Expected Result

```
root@example.com:~# dokku config hello-world
=====> hello-world env vars
KEY:    VALUE_1
KEY_2:  false
KEY_3:  TRUE

```
Actual Result

```
root@example.com:~# dokku config hello-world
=====> hello-world env vars
KEY:    VALUE_1
KEY_2:
```

Ansible error

```
fatal: [example.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to danna.bcs.io closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1555502174.761599-66741067530716/AnsiballZ_dokku_config.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1555502174.761599-66741067530716/AnsiballZ_dokku_config.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1555502174.761599-66741067530716/AnsiballZ_dokku_config.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib/python3.5/imp.py\", line 234, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib/python3.5/imp.py\", line 170, in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 626, in _exec\r\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\r\n  File \"/tmp/ansible_dokku_config_payload_8av3zap2/__main__.py\", line 143, in <module>\r\n  File \"/tmp/ansible_dokku_config_payload_8av3zap2/__main__.py\", line 135, in main\r\n  File \"/tmp/ansible_dokku_config_payload_8av3zap2/__main__.py\", line 99, in dokku_config_set\r\n  File \"/usr/lib/python3.5/shlex.py\", line 282, in quote\r\n    if _find_unsafe(s) is None:\r\nTypeError: expected string or bytes-like object\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

---

# FIX: Booleans should be quoted
  - all configurations should be treated like strings, including booleans
  - the code will be changed to error if you haven't quoted a boolean value
  
Working Boolean example is as follows: 

```
      dokku_config:
        app: hello-world
        config:
          KEY_2: "false"
```
