### ISSUE TITLE
dokku_docker_options docs differ from implemenetation on options field

### ISSUE THREAD

**Issue by jbothma** [dokku/ansible-dokku#65]
## Description of problem

dokku_docker_options documents `options` field that is a list of strings, but expects `option field that is a string

### How reproducible

Use `options` field in `dokku_docker_options` task

### Steps to Reproduce

```
    - name: "Index data mapped out to host at deploy time"
      dokku_docker_options:
        app: "{{ app_name }}"
        phase: deploy
        options:
            - "-v /var/{{ app_name }}/data:/usr/share/elasticsearch/data"
```

#### Actual Results

```
FAILED! => {"changed": false, "msg": "Unsupported parameters for (dokku_docker_options) module: options Supported parameters include: app, option, phase, state"}
```

#### Expected Results

All options in `options` list set on the app

## Environment Information

```
ansible-galaxy install --force dokku_bot.ansible_dokku,v2020.3.24
```
