### ISSUE TITLE
Implement backup configuration for services

### ISSUE THREAD

**Issue by nicolas-brousse** [dokku/ansible-dokku#8]
Do you think It may be possible to management backup configuration from a module?  
On `dokku_service_create` or maybe something like `dokku_service_backup`.

I never code with python actually, but may be I could have a look if this feature may interest you and I found some time later.

**Comment by josegonzalez** [comment]
Sure, seems interesting :)

**Comment by nicolas-brousse** [comment]
Cool!

To be honest, I'm currently not having time  to work on this kind of project.  
But since we planned to use dokku to host our customer projects, I'll have to find some time to improve our ansible playbooks. So I'll try to work on a module when I'll update our playbooks.

**Comment by nicolas-brousse** [comment]
I start thinking to this library and I've got some question before I could really work on it.

* What do you think of this structure for the configuration:
```yml
  dokku_service_backup:
    name: default
    service: redis
    state: present
    auth:
      access_key_id:
      secret_access_key:
      region:
      signature_version:
      endpoint_url:
      bucket_name:
    schedule:
    encryption:
      passphrase:
```
* About the `backup-auth`/`backup-deauth`, how to know if authentication already set, and how to manage credentials updates. There is no `dokku` command that really help us with that. The only way I saw for now, is to directly read file on server. But not sure is the cleanest way.
* For `backup-set-encryption`/`backup-unset-encryption`, I've almost the same question than for authentication. How to know if backups are already encrypted? And how to manage how to manage the passphrase update?

I never wrote python before, but it looks not really complicated. So I'll try to do a PR in the coming days. But could you tell me how do you process to test this ansible code? Manually, with a vagrant vm?
