### ISSUE TITLE
`dokku_clone` hangs indefinitely, when providing incorrect git URL

### ISSUE THREAD

**Issue by ltalirz** [dokku/ansible-dokku#92]
## Description of problem

The following `dokku_clone` task hangs indefinitely:
```yaml
- name: Create seekpath app
  dokku_clone:
    app: seekpath
    repository: https://github.com/materialscloud-org/tools-seekpath2    # <= not a github repo
```

The reason for this is that the `dokku clone` command  waits for input:
```
$ dokku clone seekpath2 https://github.com/materialscloud-org/tools-seekpath2
-----> Creating seekpath2 from https://github.com/materialscloud-org/tools-seekpath2 master
Username for 'https://github.com':
```

#### Expected Results

I would expect the `dokku_clone` module to fail, if the URL provided requires additional authentication.

It should probably pass something like a `--non-interactive` flag to the `dokku clone` command (or can the ansible module detect if the command waits for input and fail?).
